# LTO_ENABLE = yes
CONVERT_TO = elite_pi

# ENCODER_ENABLE = yes
# ENCODER_MAP_ENABLE = yes
# MOUSEKEY_ENABLE = yes

# EXTRAKEY_ENABLE = yes
# SEND_STRING_ENABLE = yes
# UNICODE_COMMON = yes

# RGBLIGHT_ENABLE = yes
# VELOCIKEY_ENABLE = yes
